In [2]:
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine("sqlite+pysqlite:///data/orders_and_users.db")
inspector = sqlalchemy.inspect(engine)
print(inspector.get_table_names())
inspector.get_columns("orders")

['customers', 'orders']

[{'name': 'InvoiceNo',
  'type': VARCHAR(),
  'nullable': True,
  'default': None,
  'primary_key': 1},
 {'name': 'CustomerID',
  'type': VARCHAR(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'Description',
  'type': VARCHAR(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'Quantity',
  'type': INTEGER(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'UnitPrice',
  'type': FLOAT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'Category',
  'type': VARCHAR(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'Discount',
  'type': FLOAT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'PaymentMethod',
  'type': VARCHAR(),
  'nullable': True,
  'default': None,
  'primary_key': 0}]

In [3]:
query = sqlalchemy.text("""
SELECT customers.Location, orders.Category, COUNT(*) AS orders_count
FROM orders
INNER JOIN customers
ON orders.CustomerID = customers.CustomerID
GROUP BY customers.Location, orders.Category
ORDER BY customers.Location, orders_count DESC
""")
orders_by_location_category = pd.read_sql(query, con=engine)
orders_by_location_category

    Location     Category  orders_count
0   Boryspil  Electronics            10
1   Boryspil       Office             5
2   Boryspil  Accessories             5
3   Boryspil       Gaming             2
4    Boyarka  Electronics             3
5    Boyarka  Accessories             1
6    Brovary  Electronics             2
7    Brovary       Office             1
8    Brovary  Accessories             1
9      Bucha  Accessories             3
10     Bucha       Office             1
11  Hostomel  Accessories             5
12  Hostomel       Office             4
13  Hostomel  Electronics             3
14  Hostomel       Gaming             2
15     Irpin  Accessories             3
16     Irpin       Office             1
17     Irpin  Electronics             1
18      Kyiv  Accessories            18
19      Kyiv  Electronics            13
20      Kyiv       Office             7
21      Kyiv       Gaming             5
22  Vyshneve  Electronics             3
23  Vyshneve  Accessories             1

In [4]:
query = sqlalchemy.text("""
SELECT customers.Location, COUNT(*) AS keyboard_orders
FROM orders
INNER JOIN customers
ON orders.CustomerID = customers.CustomerID
WHERE orders.Description = 'Gaming Keyboard'
GROUP BY customers.Location
ORDER BY keyboard_orders DESC
""")
keyboards_by_location = pd.read_sql(query, con=engine)
keyboards_by_location

   Location  keyboard_orders
0      Kyiv                5
1  Hostomel                2
2  Boryspil                2

In [5]:
query = sqlalchemy.text("""
SELECT orders.Category, COUNT(*) AS orders_count
FROM orders
INNER JOIN customers
ON orders.CustomerID = customers.CustomerID
WHERE customers.Annual_Income > 2000
GROUP BY orders.Category
ORDER BY orders_count DESC
""")
category_income_2000 = pd.read_sql(query, con=engine)
category_income_2000

      Category  orders_count
0  Electronics            11
1  Accessories            11
2       Office             6
3       Gaming             4